# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v1.0.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
