# Deploy snapshots to Sonatpe OSS repository and deploy site to GitHub Pages

name: Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure GIT
        run: |
          git config --global user.email "${{ secrets.GH_SITE_DEPLOY_EMAIL }}"
          git config --global user.name "${{ secrets.GH_SITE_DEPLOY_NAME }}"

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
          cache: 'maven'

      - name: Build, verify, deploy, generate site
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: mvn -s ./.maven-settings.xml -Pcontinuous-integration -B -U clean deploy site

      # Deploy site to Github Pages
      # WORKAROUND for https://issues.apache.org/jira/browse/MSCMPUB-18 - deploy site in multiple steps for subset of modules
      - name: Stage and deploy site - Part 1
        run: >
          mvn -s ./.maven-settings.xml -Pcontinuous-integration -B site:stage scm-publish:publish-scm
          --projects '.,parent,modules,modules/core,modules/selectors,modules/differences'
          -Dscmpublish.checkinComment="Maven site: ${{ github.repository }} - Part 1"
          -Dusername=${{ secrets.GH_SITE_DEPLOY_USERNAME }}
          -Dpassword=${{ secrets.GH_SITE_DEPLOY_PAT }}
      - name: Stage and deploy site - Part 2
        run: >
          mvn -s ./.maven-settings.xml -Pcontinuous-integration -B site:stage scm-publish:publish-scm
          --projects '.,modules/interaction,modules/listeners,modules/galen,maven/specs-plugin'
          -Dscmpublish.checkinComment="Maven site: ${{ github.repository }} - Part 2"
          -Dusername=${{ secrets.GH_SITE_DEPLOY_USERNAME }}
          -Dpassword=${{ secrets.GH_SITE_DEPLOY_PAT }}
      - name: Stage and deploy site - Part 3
        run: >
          mvn -s ./.maven-settings.xml -Pcontinuous-integration -B site:stage scm-publish:publish-scm
          --projects '!parent,!modules,!modules/core,!modules/selectors,!modules/differences,!modules/interaction,!modules/listeners,!modules/galen,!maven/specs-plugin'
          -Dscmpublish.checkinComment="Maven site: ${{ github.repository }} - Part 3"
          -Dusername=${{ secrets.GH_SITE_DEPLOY_USERNAME }}
          -Dpassword=${{ secrets.GH_SITE_DEPLOY_PAT }}
